---
- hosts: localhost
  become: yes
  connection: local
  tasks:
  - name: i want to create autoscalling group 
    ec2_asg:
      name: redgreek_web_asg
      launch_config_name: sample
      region: us-west-2
      load_balancers: redgreekwebelb
      availability_zones: [ 'us-west-2b']
      min_size: 1
      max_size: 1
      desired_capacity: 1
      replace_all-instances: yes
      vpc_zone_identifier: [' subnet-88898df1 ']
      tags:
       - type: redgeek_web_server
         wait_for_instances: yes   

