---
- hosts: localhost
  become: yes
  connection: local
  tasks:
  - name: i want to create autoscalling group 
    ec2_asg:
      name: redgreek_web_asg
      launch_config_name: sample2
      health_check_period: 60
      health_check_type: ELB
      region: us-west-2
      load_balancers: redgreekwebelb
      availability_zones: [ 'us-west-2b','us-west-2d']
      min_size: 1
      max_size: 1
      desired_capacity: 1
      replace_all_instances: yes
      vpc_zone_identifier: [' subnet-88898df1 ','subnet-194dc332' ]
      tags:
       - type: redgeek_web_server
         wait_for_instances: yes   

