---
- hosts: localhost
  tasks:
  - name: gather facts
    ec2_elb_facts:
      region: us-west-2
      name: redgeekwebelb
    register: elb_facts

  - debug:
      msg: "{{ elb_facts.elbs.0.dns_name}} "

  - url:
     url: http://{{ elb_facts.elbs.o.dns_name}}
     return_content: yes
     register: this
     failed_when: * 'hello from ASG' not in this content

